---
title: "ISU Monarch Data Summary for Iowa NRCS"
author: "Jarad Niemi"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{ISU Monarch Data Summary for Iowa NRCS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, message=FALSE, echo=FALSE}
library(dplyr)
library(ISUmonarch)
library(xtable)
options(xtable.comment = FALSE)
```

```{r sites, echo=FALSE}
sites = c("byd1", "byd2", "cra1", "uth1", "uth2", "uth3")
```


## Nectar

```{r nectar, results='asis', echo=FALSE}
nectar %>%
  filter(site %in% sites) %>%
  group_by(`Nectar Plant Species`, round, site) %>%
  summarize(total = sum(count)) %>%
  tidyr::spread(site, total, fill='.') %>%
  arrange(round, `Nectar Plant Species`) %>% 
  mutate(uth1 = ".") %>%
  select(`Nectar Plant Species`, round, byd1, byd2, cra1, uth1, uth2, uth3) %>%
  xtable(align = "clc|rrrrrr") %>%
  print(include.rownames = FALSE,
        hline.after = c(-1,0,9,21,32)) # type="html" for html file
```

\newpage
Nectar density

```{r nectar_density, results='asis', echo=FALSE}
nectar %>%
  filter(site %in% sites) %>%
  group_by(`Nectar Plant Species`, round, site) %>%
  summarize(total = sum(count)) %>%
  mutate(total = round(ifelse(site=="cra1", total/70, total/100),2)) %>%
  tidyr::spread(site, total, fill='.') %>%
  arrange(round, `Nectar Plant Species`) %>% 
  mutate(uth1 = ".") %>%
  select(`Nectar Plant Species`, round, byd1, byd2, cra1, uth1, uth2, uth3) %>%
  xtable(align = "clc|rrrrrr") %>%
  print(include.rownames = FALSE,
        hline.after = c(-1,0,9,21,32)) # type="html" for html file
```


\newpage
## Daubenmire

```{r daubenmire, results='asis', echo=FALSE}
daubenmire_round_average = daubenmire %>%
  filter(site %in% sites) %>% 
  mutate(land_cover = factor(land_cover, 
                            levels=c("csg",
                                     "wsg",
                                     "forbs",
                                     "milkweed",
                                     "woody_species",
                                     "bare_ground",
                                     "leaf_litter",
                                     "litter_depth")),
         land_cover = recode(land_cover, 
                             csg = "cool season grass",
                             wsg = "warm season grass",
                             litter_depth = "litter depth (cm)")) %>%
  group_by(land_cover, round, site) %>%
  summarize(mean_percentage = round(mean(percentage),1))  

daubenmire_round_average %>%
  mutate(mean_percentage = round(mean_percentage,1))  %>%
  tidyr::spread(site, mean_percentage, fill='na') %>%
  ungroup() %>% 
  arrange(round, land_cover) %>% 
  xtable(align = "clc|rrrrrr") %>%
  print(include.rownames = FALSE,
        hline.after = c(-1,0,8,16,24)) # type="html" for html file
```

Averaged across rounds

```{r daubenmire_average, results='asis', echo=FALSE}
daubenmire_round_average %>% 
  group_by(land_cover, site) %>%
  summarize(mean_percentage = round(mean(mean_percentage),1)) %>% 
  tidyr::spread(site, mean_percentage, fill='na') %>%
  ungroup() %>% 
  arrange(land_cover) %>% 
  xtable(align="cl|rrrrrr") %>%
  print(include.rownames = FALSE) # type="html" for html file
```

\newpage

Averaged across sites and rounds

```{r daubenmire_average2, results='asis', echo=FALSE}
daubenmire_round_average %>% 
  group_by(land_cover) %>%
  summarize(mean_percentage = round(mean(mean_percentage),1)) %>% 
  ungroup() %>% 
  arrange(land_cover) %>% 
  xtable() %>%
  print(include.rownames = FALSE) # type="html" for html file
```


## Robel

```{r robel, results='asis', echo=FALSE}
robel %>%
  filter(site %in% sites) %>%
  group_by(round, site) %>%
  summarize(mean_count = round(mean(count),1)) %>%
  tidyr::spread(site, mean_count, fill='na') %>%
  xtable() %>%
  print(include.rownames = FALSE) # type="html" for html file
```

Average across all rounds

```{r robel_average, results='asis', echo=FALSE}
robel %>%
  filter(site %in% sites) %>%
  group_by(round, site) %>%
  summarize(mean_count = mean(count)) %>%
  group_by(site) %>%
  summarize(mean_count = round(mean(mean_count),1)) %>%
  tidyr::spread(site, mean_count, fill='na') %>%
  xtable() %>%
  print(include.rownames = FALSE) # type="html" for html file
```

\newpage

## Monarch

Adults

```{r monarch_adults, results='asis', echo=FALSE}
monarch %>%
  filter(site %in% sites) %>%
  filter(!grepl("instar", distance)) %>%
  filter(distance != "stems") %>%
  filter(distance != "eggs") %>%
  group_by(site) %>%
  summarize(sum_no_extra = sum(count[distance != "extra_monarch"]),
            sum_all      = sum(count)) %>%
  tidyr::gather("Adult monarchs", count, -site) %>%
  tidyr::spread(site, count) %>%
  xtable() %>%
  print() # type="html" for html file
```

Stems

```{r monarch_stems, results='asis', echo=FALSE}
monarch %>%
  filter(site %in% sites) %>%
  filter(distance == "stems") %>%
  group_by(site) %>%
  summarize(mean = round(mean(count),1)) %>%
  tidyr::spread(site, mean, fill='na') %>%
  xtable() %>%
  print(include.rownames = FALSE) # type="html" for html file
```

Eggs

```{r monarch_eggs, results='asis', echo=FALSE}
monarch %>%
  filter(site %in% sites) %>%
  filter(distance == "eggs") %>%
  group_by(site) %>%
  summarize(total = sum(count)) %>%
  tidyr::spread(site, total, fill='na') %>%
  xtable() %>%
  print(include.rownames = FALSE) # type="html" for html file
```


Instar
```{r monarch_instar, results='asis', echo=FALSE}
monarch %>%
  filter(site %in% sites) %>%
  filter(grepl("instar", distance)) %>%
  group_by(site) %>%
  summarize(total = sum(count)) %>%
  tidyr::spread(site, total, fill='na') %>%
  xtable() %>%
  print(include.rownames = FALSE,
        table.placement = "!h") # type="html" for html file
```



## Bee

Total number of bees observed.

```{r bee, results='asis', echo=FALSE}
bee %>%
  filter(site %in% sites) %>%
  group_by(site) %>%
  summarize(sum = sum(count)) %>%
  tidyr::spread(site, sum) %>% 
  mutate(byd1 = 0, uth1 = 0) %>%
  select_("byd1","byd2","cra1","uth1","uth2","uth3") %>% 
  xtable(digits=0) %>%
  print(include.rownames=FALSE,
        table.placement = "!h") # type="html" for html file
```


## Environment

Did any survey at each site reveal milkweed or flowering plants?

```{r environment, results='asis', echo=FALSE}
environment %>%
  filter(site %in% sites) %>%
  group_by(site) %>%
  summarize(milkweed      = any(milkweed == "yes"),
            flower_plants = any(flowering_plants == "yes")) %>%
  tidyr::gather(plant, bool, -site) %>%
  mutate(bool = ifelse(bool, "Yes", "No")) %>%
  tidyr::spread(site, bool) %>%
  xtable() %>%
  print(table.placement = "!h") # type="html" for html file
```


