source("bee.R")
source("daubenmire.R")
source("survey.R")
source("monarch.R")
source("nectar.R")
source("robel.R")
source("species.R")

source("environment.R")
source("landscape2016.R")
source("transect.R")
