---
title: "ISU Monarch Data Summary for NCIG"
author: "Jarad Niemi"
date: "`r Sys.Date()`"
header-includes:
  - \usepackage{rotating}
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{ISU Monarch Data Summary for NCIG}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, purl=FALSE, echo=FALSE}
library("knitr")
opts_chunk$set(echo=FALSE, 
               results = 'asis',
               message = FALSE)
```

```{r packages}
library(dplyr)
library(ISUmonarch)
library(xtable)
options(xtable.comment = FALSE)
```

```{r sites}
sites = c("all1","all2","arm2","ber1","ber3","cre1","dun2","dun3",
          "pio1","pio2","gro1","gro2","nkn1","nkn2","nor1","sut1","sie1",
          "prd1","prd2","var1")
```



## Nectar

```{r nectar}
nectar %>%
  filter(site %in% sites) %>%
  group_by(`Nectar Plant Species`, site) %>%
  summarize(total = mean(count) %>% round(1)) %>%
  tidyr::spread(site, total, fill=NA) %>%
  arrange(`Nectar Plant Species`) %>% 
  # select_("`Nectar Plant Species`", sites) %>%
  xtable(digits = 1,
         caption="Nectar plant species: mean count across all surveys") %>%
  print(include.rownames = FALSE, NA.string="-") 
```




\newpage
Nectar density

```{r nectar_density}
nectar %>%
  filter(site %in% sites) %>%
  group_by(`Nectar Plant Species`, site) %>%
  summarize(count = sum(count)) %>%
  ungroup() %>%
  left_join(ISUmonarch::length) %>%
  mutate(density = 100*count / length) %>%
  select(-count, -length) %>%
  tidyr::spread(site, density, fill=NA) %>%
  arrange(`Nectar Plant Species`) %>% 
  # select_("`Nectar Plant Species`", sites) %>%
  xtable(digits = 0,
         caption="Nectar plant species density: average density (count / 100 m2) across all rounds") %>%
  print(include.rownames = FALSE, NA.string="-") 
```


\newpage
## Daubenmire

```{r daubenmire}
daubenmire_average <- daubenmire %>%
  filter(site %in% sites) %>% 
  mutate(land_cover = factor(land_cover, 
                            levels=c("csg",
                                     "wsg",
                                     "forbs",
                                     "milkweed",
                                     "woody_species",
                                     "bare_ground",
                                     "leaf_litter",
                                     "litter_depth")),
         land_cover = recode(land_cover, 
                             csg = "cool season grass",
                             wsg = "warm season grass",
                             litter_depth = "litter depth (cm)")) %>%
  group_by(land_cover, site) %>%
  summarize(mean_percentage = round(mean(percentage),1))  

daubenmire_average %>%
  mutate(mean_percentage = round(mean_percentage,1))  %>%
  tidyr::spread(land_cover, mean_percentage, fill=NA) %>%
  ungroup() %>% 
  arrange(site) %>% 
  xtable(digits = 1,
         caption="Daubenmire: average land cover \\% across all rounds") %>%
  print(include.rownames = FALSE, NA.string="na",
        rotate.colnames = TRUE) 
```

\newpage

Averaged across sites 

```{r daubenmire_average2}
daubenmire_average %>% 
  group_by(land_cover) %>%
  summarize(average = round(mean(mean_percentage),1)) %>% 
  ungroup() %>% 
  tidyr::spread(land_cover, average) %>%
  xtable(caption="Daubenmire: average land cover \\% across all rounds and sites") %>%
  print(include.rownames = FALSE,
        rotate.colnames = TRUE) 
```


## Robel

```{r robel_average}
robel %>%
  filter(site %in% sites) %>%
  group_by(round, site) %>%
  summarize(mean_count = mean(count)) %>%
  group_by(site) %>%
  summarize(average = mean(mean_count)) %>%
  # tidyr::spread(site, mean_count, fill='na') %>%
  xtable(digits = 1,
         caption="Robel: average across all rounds") %>%
  print(include.rownames = FALSE) 
```

\newpage

## Monarch

```{r}
monarch %>% 
  filter(site %in% sites) %>%
  mutate(group = "survey",
         group = ifelse(grepl("instar",distance), "instar", group),
         group = ifelse(distance == "stems",      "stems" , group),
         group = ifelse(distance == "eggs",       "eggs"  , group),
         group = ifelse(distance == "extra_monarch", "extra", group),
         group = ifelse(distance == "watch_monarch", "watch", group)) %>%
  select(site, group, count) %>%
  group_by(site, group) %>%
  summarize(count = sum(count)) %>%
  tidyr::spread(group,count, fill=0) %>%
  mutate(Total  = survey + extra) %>%
  ungroup() %>%
  rename(Survey = survey,
         Stems = stems,
         Eggs = eggs,
         Instar = instar) %>%
  select(site, Total, Survey, Instar, Stems, Eggs) %>%
  xtable(digits = 0,
         caption="Monarch: adults, instar, stems, and eggs") %>%
  print(include.rownames = FALSE,
        add.to.row = list(pos = list(-1), 
                          command = "& \\multicolumn{2}{c}{Adults} \\\\")) 
```



```{r monarch_adults}
monarch %>%
  filter(site %in% sites) %>%
  filter(!grepl("instar", distance)) %>%
  filter(distance != "stems") %>%
  filter(distance != "eggs") %>%
  group_by(site) %>%
  summarize(`without extras` = sum(count[distance != "extra_monarch"]),
            Total      = sum(count)) %>%
  tidyr::gather("Adult monarchs", count, -site) %>%
  tidyr::spread(`Adult monarchs`, count) %>%
  xtable(digits = 0,
         caption = "Adult monarchs") %>%
  print(include.rownames=FALSE) 
```

Stems

```{r monarch_stems}
monarch %>%
  filter(site %in% sites) %>%
  filter(distance == "stems") %>%
  group_by(site) %>%
  summarize(mean = round(mean(count),1)) %>%
  xtable(digits = 1,
         caption = "Stems") %>%
  print(include.rownames = FALSE) 
```

Eggs

```{r monarch_eggs}
monarch %>%
  filter(site %in% sites) %>%
  filter(distance == "eggs") %>%
  group_by(site) %>%
  summarize(total = sum(count)) %>%
  xtable(digits=0,
         caption = "Eggs") %>%
  print(include.rownames = FALSE) 
```


Instar
```{r monarch_instar}
monarch %>%
  filter(site %in% sites) %>%
  filter(grepl("instar", distance)) %>%
  group_by(site) %>%
  summarize(total = sum(count)) %>%
  xtable(digits=0,
         caption = "Instar") %>%
  print(include.rownames = FALSE,
        table.placement = "!h") 
```


## Environment

Did any survey at each site reveal milkweed or flowering plants?

```{r environment}
environment %>%
  filter(site %in% sites) %>%
  group_by(site) %>%
  summarize(milkweed           = any(milkweed == "yes"),
            `flowering plants` = any(flowering_plants == "yes")) %>%
  tidyr::gather(plant, bool, -site) %>%
  mutate(bool = ifelse(bool, "Yes", "--")) %>%
  rename(present = bool) %>%
  tidyr::spread(plant, present) %>%
  arrange(site) %>%
  xtable() %>%
  print(include.rownames=FALSE, table.placement = "!h") 
```


