---
title: "ISU Monarch Data Summary for Iowa NRCS"
author: "Jarad Niemi"
date: "`r Sys.Date()`"
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{ISU Monarch Data Summary for Iowa NRCS}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, message=FALSE, echo=FALSE}
library(dplyr)
library(ISUmonarch)
library(xtable)
options(xtable.comment = FALSE)
```

```{r sites, echo=FALSE}
sites = c("byd1", "byd2", "cra1", "uth1", "uth2", "uth3")
```


## Nectar

```{r nectar, results='asis', echo=FALSE}
nectar %>%
  filter(site %in% sites) %>%
  group_by(`Nectar Plant Species`, round, site) %>%
  summarize(total = sum(count)) %>%
  tidyr::spread(site, total, fill='.') %>%
  arrange(round, `Nectar Plant Species`) %>% 
  xtable() %>%
  print(include.rownames = FALSE) # type="html" for html file
```

\newpage
## Daubenmire

```{r daubenmire, results='asis', echo=FALSE}
daubenmire_round_average = daubenmire %>%
  filter(site %in% sites) %>% 
  mutate(something = factor(something, 
                            levels=c("csg",
                                     "wsg",
                                     "forbs",
                                     "milkweed",
                                     "woody_species",
                                     "bare_ground",
                                     "leaf_litter",
                                     "litter_depth"))) %>%
  group_by(something, round, site) %>%
  summarize(mean_percentage = round(mean(percentage),1))  

daubenmire_round_average %>%
  mutate(mean_percentage = round(mean_percentage,1))  %>%
  tidyr::spread(site, mean_percentage, fill='.') %>%
  ungroup() %>% 
  arrange(round, something) %>% 
  xtable() %>%
  print(include.rownames = FALSE) # type="html" for html file
```

Averaged across rounds

```{r daubenmire_average, results='asis', echo=FALSE}
daubenmire_round_average %>% 
  group_by(something, site) %>%
  summarize(mean_percentage = round(mean(mean_percentage),1)) %>% 
  tidyr::spread(site, mean_percentage, fill='.') %>%
  ungroup() %>% 
  arrange(something) %>% 
  xtable() %>%
  print(include.rownames = FALSE) # type="html" for html file
```

\newpage

Averaged across sites and rounds

```{r daubenmire_average2, results='asis', echo=FALSE}
daubenmire_round_average %>% 
  group_by(something) %>%
  summarize(mean_percentage = round(mean(mean_percentage),1)) %>% 
  ungroup() %>% 
  arrange(something) %>% 
  xtable() %>%
  print(include.rownames = FALSE) # type="html" for html file
```


\newpage